#!/bin/bash
# pre-commit-wiki-sync.sh — Enforce wiki/ sync on docs/ changes
# Called by Claude Code PreToolUse hook (Bash tool with git commit)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
STAMP_FILE="$PROJECT_ROOT/.wiki-sync-stamp"
SYNC_SCRIPT="$PROJECT_ROOT/scripts/sync-wiki.sh"

cd "$PROJECT_ROOT"

# Get staged files
STAGED_FILES=$(git diff --cached --name-only 2>/dev/null || echo "")

if [ -z "$STAGED_FILES" ]; then
    exit 0
fi

ERRORS=""

# Rule 1: If docs/ changed, wiki/ must be synced
DOCS_CHANGED=$(echo "$STAGED_FILES" | grep "^docs/" || true)
if [ -n "$DOCS_CHANGED" ]; then
    if [ ! -f "$STAMP_FILE" ]; then
        ERRORS="${ERRORS}ERROR: docs/ files changed but wiki/ never synced.\n  Run: ./scripts/sync-wiki.sh\n\n"
    else
        STAMP_TIME=$(cat "$STAMP_FILE")
        # Check if any docs/ file is newer than stamp
        for f in $DOCS_CHANGED; do
            if [ -f "$f" ] && [ "$f" -nt "$STAMP_FILE" ]; then
                ERRORS="${ERRORS}ERROR: $f changed after last wiki sync ($STAMP_TIME).\n  Run: ./scripts/sync-wiki.sh\n\n"
                break
            fi
        done
    fi
fi

# Rule 2: wiki/ files must not be manually edited (unless auto-generated)
WIKI_CHANGED=$(echo "$STAGED_FILES" | grep "^wiki/" || true)
if [ -n "$WIKI_CHANGED" ]; then
    for f in $WIKI_CHANGED; do
        if [ -f "$f" ]; then
            if ! head -1 "$f" | grep -q "AUTO-GENERATED:"; then
                ERRORS="${ERRORS}ERROR: $f is manually edited (no AUTO-GENERATED marker).\n  wiki/ is a read-only derived view. Modify docs/ and run ./scripts/sync-wiki.sh\n\n"
            fi
        fi
    done
fi

# Rule 3: DEVELOPMENT_STATUS.md must not be manually edited
STATUS_CHANGED=$(echo "$STAGED_FILES" | grep "\.claude/DEVELOPMENT_STATUS\.md$" || true)
if [ -n "$STATUS_CHANGED" ]; then
    STATUS_FILE="$PROJECT_ROOT/.claude/DEVELOPMENT_STATUS.md"
    if [ -f "$STATUS_FILE" ] && ! head -1 "$STATUS_FILE" | grep -q "AUTO-GENERATED:"; then
        ERRORS="${ERRORS}ERROR: .claude/DEVELOPMENT_STATUS.md is manually edited.\n  This file is auto-generated by Stop hook. Revert changes.\n\n"
    fi
fi

# Report errors
if [ -n "$ERRORS" ]; then
    echo ""
    echo "=========================================="
    echo "  Wiki Sync Enforcement — BLOCKED"
    echo "=========================================="
    echo ""
    echo -e "$ERRORS"
    exit 1
fi

exit 0
