server:
  port: 8086

spring:
  application:
    name: schemaplexai-spec
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/schemaplexai
    username: ${DB_USERNAME:?required}
    password: ${DB_PASSWORD:?required}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.schemaplexai.spec.**.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.schemaplexai.spec: debug

management:
  otlp:
    tracing:
      endpoint: http://jaeger:4318/v1/traces
      enabled: true
