#!/bin/bash
# pre-commit-wiki-sync.sh — Enforce wiki/ sync on docs/ changes
# Called by Claude Code PreToolUse hook (Bash tool with git commit)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
STAMP_FILE="$PROJECT_ROOT/.wiki-sync-stamp"
SYNC_SCRIPT="$PROJECT_ROOT/scripts/sync-wiki.sh"

cd "$PROJECT_ROOT"

# Get staged files
STAGED_FILES=$(git diff --cached --name-only 2>/dev/null || echo "")

if [ -z "$STAGED_FILES" ]; then
    exit 0
fi

ERRORS=""

# Rule 1: If docs/ changed, wiki/ must be synced
DOCS_CHANGED=$(echo "$STAGED_FILES" | grep "^docs/" || true)
if [ -n "$DOCS_CHANGED" ]; then
    if [ ! -f "$STAMP_FILE" ]; then
        ERRORS="${ERRORS}ERROR: docs/ files changed but wiki/ never synced.\n  Run: ./scripts/sync-wiki.sh\n\n"
    else
        STAMP_TIME=$(cat "$STAMP_FILE")
        # Check if any docs/ file is newer than stamp
        for f in $DOCS_CHANGED; do
            if [ -f "$f" ] && [ "$f" -nt "$STAMP_FILE" ]; then
                ERRORS="${ERRORS}ERROR: $f changed after last wiki sync ($STAMP_TIME).\n  Run: ./scripts/sync-wiki.sh\n\n"
                break
            fi
        done
    fi
fi

# Rule 2: wiki/ files must not be manually edited (unless auto-generated)
WIKI_CHANGED=$(echo "$STAGED_FILES" | grep "^wiki/" || true)
if [ -n "$WIKI_CHANGED" ]; then
    for f in $WIKI_CHANGED; do
        if [ -f "$f" ]; then
            if ! head -1 "$f" | grep -q "AUTO-GENERATED:"; then
                ERRORS="${ERRORS}ERROR: $f is manually edited (no AUTO-GENERATED marker).\n  wiki/ is a read-only derived view. Modify docs/ and run ./scripts/sync-wiki.sh\n\n"
            fi
        fi
    done
fi

# Rule 3: DEVELOPMENT_STATUS.md must not be manually edited
STATUS_CHANGED=$(echo "$STAGED_FILES" | grep "\.claude/DEVELOPMENT_STATUS\.md$" || true)
if [ -n "$STATUS_CHANGED" ]; then
    STATUS_FILE="$PROJECT_ROOT/.claude/DEVELOPMENT_STATUS.md"
    if [ -f "$STATUS_FILE" ] && ! head -1 "$STATUS_FILE" | grep -q "AUTO-GENERATED:"; then
        ERRORS="${ERRORS}ERROR: .claude/DEVELOPMENT_STATUS.md is manually edited.\n  This file is auto-generated by Stop hook. Revert changes.\n\n"
    fi
fi

# Rule 4: review-verdict gate for workflow-adopter Deliver phase
CHANGES_STAGED=$(echo "$STAGED_FILES" | grep "^\\.claude/changes/" || true)
if [ -n "$CHANGES_STAGED" ]; then
    FEATURE_DIRS=$(echo "$CHANGES_STAGED" | awk -F'/' '{print $3}' | sort -u)
    for feat in $FEATURE_DIRS; do
        VERDICT_DIR=".claude/changes/$feat"
        for verdict_file in "$VERDICT_DIR/review-verdict.json" "$VERDICT_DIR/security-verdict.json"; do
            if [ -f "$verdict_file" ]; then
                if command -v jq >/dev/null 2>&1; then
                    VERDICT=$(jq -r '.verdict // "missing"' "$verdict_file")
                    CRITICAL_COUNT=$(jq '[.issues[]?.severity // empty | select(. == "CRITICAL")] | length' "$verdict_file")
                else
                    VERDICT=$(grep -o '"verdict"[[:space:]]*:[[:space:]]*"[^"]*"' "$verdict_file" | head -1 | sed 's/.*"verdict"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
                    CRITICAL_COUNT=$(grep -c '"severity"[[:space:]]*:[[:space:]]*"CRITICAL"' "$verdict_file" || true)
                fi
                if [ "$VERDICT" = "blocked" ]; then
                    ERRORS="${ERRORS}ERROR: $verdict_file verdict is BLOCKED. Fix before commit.\n\n"
                fi
                if [ "$CRITICAL_COUNT" -gt 0 ] 2>/dev/null; then
                    ERRORS="${ERRORS}ERROR: $verdict_file contains $CRITICAL_COUNT CRITICAL issue(s). Fix before commit.\n\n"
                fi
            fi
        done
    done
fi

# Report errors
if [ -n "$ERRORS" ]; then
    echo ""
    echo "=========================================="
    echo "  Wiki Sync Enforcement — BLOCKED"
    echo "=========================================="
    echo ""
    echo -e "$ERRORS"
    exit 1
fi

# Clear docs-dirty marker on successful commit
: > .claude/outputs/.docs-dirty 2>/dev/null || true

exit 0
