import type { ThemeConfig } from 'antd'

export const abyssHiveTheme: ThemeConfig = {
  token: {
    colorBgBase: '#0a0e1a',
    colorBgContainer: '#111827',
    colorBgElevated: '#111827',
    colorBgLayout: '#0a0e1a',
    colorBorder: '#1e2a33',
    colorBorderSecondary: '#1e2a3380',
    colorPrimary: '#00d4aa',
    colorError: '#ff4757',
    colorWarning: '#ff9f43',
    colorSuccess: '#00d4aa',
    colorText: '#e2e8f0',
    colorTextSecondary: '#64748b',
    colorTextTertiary: '#475569',
    colorTextPlaceholder: '#475569',
    colorLink: '#00d4aa',
    colorLinkHover: '#00f5c4',
    colorLinkActive: '#00b894',
    fontFamily: "'Inter', 'Noto Sans SC', 'PingFang SC', 'Microsoft YaHei', sans-serif",
    fontFamilyCode: "'JetBrains Mono', 'Fira Code', monospace",
    fontSize: 14,
    fontSizeSM: 12,
    fontSizeLG: 16,
    fontSizeXL: 20,
    borderRadius: 8,
    borderRadiusSM: 4,
    borderRadiusLG: 12,
    paddingXS: 8,
    paddingSM: 12,
    padding: 16,
    paddingMD: 20,
    paddingLG: 24,
    paddingXL: 32,
    controlHeight: 40,
    controlHeightSM: 32,
    controlHeightLG: 48,
  },
  components: {
    Card: {
      colorBgContainer: '#111827',
      borderRadius: 8,
      headerBg: 'transparent',
      headerFontSize: 16,
      actionsBg: 'transparent',
    },
    Button: {
      borderRadius: 6,
      borderRadiusSM: 4,
      primaryShadow: '0 0 12px #00d4aa30',
      dangerShadow: '0 0 12px #ff475730',
    },
    Table: {
      headerBg: '#0d1117',
      headerColor: '#64748b',
      headerSplitColor: '#1e2a33',
      rowHoverBg: '#111827',
      borderColor: '#1e2a3380',
      cellPaddingBlock: 12,
      cellPaddingInline: 16,
    },
    Input: {
      colorBgContainer: 'transparent',
      colorBorder: '#1e2a33',
      activeBorderColor: '#00d4aa',
      activeShadow: '0 0 0 1px #00d4aa20, 0 0 12px #00d4aa15',
      borderRadius: 8,
      colorTextPlaceholder: '#475569',
      errorActiveShadow: '0 0 0 1px #ff475720',
      hoverBorderColor: '#1e3a5f',
    },
    Select: {
      colorBgContainer: 'transparent',
      colorBorder: '#1e2a33',
      borderRadius: 8,
      optionSelectedBg: '#00d4aa20',
      optionActiveBg: '#1e3a5f',
    },
    Modal: {
      colorBgElevated: '#111827',
      borderRadius: 12,
      headerBg: 'transparent',
      contentBg: '#111827',
    },
    Drawer: {
      colorBgElevated: '#111827',
    },
    Tag: {
      borderRadius: 4,
      defaultBg: 'transparent',
    },
    Tabs: {
      colorBgContainer: 'transparent',
      inkBarColor: '#00d4aa',
      itemActiveColor: '#00d4aa',
      itemHoverColor: '#00f5c4',
      itemColor: '#64748b',
    },
    Tooltip: {
      colorBgSpotlight: '#111827',
      colorTextLightSolid: '#e2e8f0',
    },
    Menu: {
      colorBgContainer: '#0d1117',
      colorItemBgSelected: '#111827',
      colorItemText: '#64748b',
      colorItemTextSelected: '#e2e8f0',
      colorItemTextHover: '#e2e8f0',
      colorActiveBarWidth: 3,
      colorActiveBarBorderSize: 0,
    },
    Switch: {
      colorPrimary: '#00d4aa',
      colorPrimaryHover: '#00f5c4',
    },
    Slider: {
      trackBg: '#00d4aa',
      trackHoverBg: '#00f5c4',
      handleColor: '#00d4aa',
    },
    Progress: {
      defaultColor: '#00d4aa',
      remainingColor: '#1e2a33',
    },
  },
}
