#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

banner "RuleOps GitHub Shadow setup"

stage "准备已发布的运行时与规则包"
say "此向导只配置 GitHub Actions 的公开仓库变量，不保存令牌、不写本地 .env。"
say "请先准备可由 GitHub-hosted runner 访问的 HTTPS tar.gz 地址，以及发布方提供的 SHA-256。"
step "输入 RuleOps runtime 发布包地址。"
ask RULEOPS_RUNTIME_URL "Runtime URL:"
step "输入 runtime 发布包的 64 位十六进制 SHA-256。"
ask RULEOPS_RUNTIME_SHA256 "Runtime SHA-256:"
step "输入 RuleBundle 发布包地址。"
ask RULEOPS_RULE_BUNDLE_URL "RuleBundle URL:"
step "输入 RuleBundle 发布包的 64 位十六进制 SHA-256。"
ask RULEOPS_RULE_BUNDLE_SHA256 "RuleBundle SHA-256:"
if [[ ! "$RULEOPS_RUNTIME_URL" =~ ^https:// ]] ||
   [[ ! "$RULEOPS_RULE_BUNDLE_URL" =~ ^https:// ]] ||
   [[ ! "$RULEOPS_RUNTIME_SHA256" =~ ^[[:xdigit:]]{64}$ ]] ||
   [[ ! "$RULEOPS_RULE_BUNDLE_SHA256" =~ ^[[:xdigit:]]{64}$ ]]; then
  warn "地址必须使用 HTTPS，两个 SHA-256 必须各为 64 位十六进制字符串。"
  exit 2
fi
note "向导不会替你发布这两个包；地址和摘要必须来自受信任的发布流程。"
pause "确认输入无误后按 Enter"

stage "写入 GitHub 仓库变量"
say "请在目标仓库的 checkout 根目录运行本向导，并确认 gh 已登录且具有仓库写权限。"
step "输入目标 GitHub 仓库地址，例如 https://github.com/OWNER/REPO。"
ask REPO_URL "Repository URL:"
REPO_URL="${REPO_URL%/}"
if [[ ! "$REPO_URL" =~ ^https://github\.com/[^/]+/[^/]+$ ]]; then
  warn "仓库地址格式不正确：$REPO_URL"
  exit 2
fi
open_url "$REPO_URL/settings/variables/actions"
note "该页面用于核对变量；实际写入由 gh variable set 完成，目标由当前 checkout 的 GitHub remote 决定。"
set_var RULEOPS_SHADOW_ENABLED "true"
set_var RULEOPS_RUNTIME_URL "$RULEOPS_RUNTIME_URL"
set_var RULEOPS_RUNTIME_SHA256 "$RULEOPS_RUNTIME_SHA256"
set_var RULEOPS_RULE_BUNDLE_URL "$RULEOPS_RULE_BUNDLE_URL"
set_var RULEOPS_RULE_BUNDLE_SHA256 "$RULEOPS_RULE_BUNDLE_SHA256"
pause "确认页面中已出现 5 个 RULEOPS_* 变量后按 Enter"

stage "确认 Actions 权限边界"
say "Shadow 工作流只读、非阻断，不创建检查状态，不评论 PR，也不上传源代码。"
open_url "$REPO_URL/settings/actions"
step "确认 Actions 已启用，并允许仓库工作流以只读方式读取内容。"
step "不要为 RuleOps 增加 contents: write、pull-requests: write 或其他写权限。"
if confirm "已检查 Actions 设置并保持只读权限？"; then
  note "已确认只读权限边界。"
else
  SKIPPED+=("确认 GitHub Actions 只读权限")
  warn "请在启用真实接入前完成权限检查。"
fi

stage "执行第一次 Shadow 验证"
say "首次运行只验证接入链路与证据产物，不把扫描结果接入合并门禁。"
open_url "$REPO_URL/actions/workflows/ruleops-shadow.yml"
step "选择 Run workflow，在目标分支上手动运行一次。"
step "打开本次运行的 ruleops-shadow-* artifact，检查 config.yaml、doctor.json、scan.json 和 shadow-status.txt。"
step "scan.json 中的 LOCAL_UNATTESTED 或 workspace facts 不完整，表示当前仍是 Shadow 证据，不是成功认证。"
if confirm "已看到完整 artifact，并确认 scan/doctor 结果可追溯？"; then
  note "首次 Shadow 运行已人工确认。"
else
  SKIPPED+=("复核第一次 RuleOps Shadow artifact")
  warn "请修复下载、摘要、配置或运行时问题后再继续。"
fi

stage "保持非阻断"
say "在证据窗口和真实项目样本稳定前，RuleOps 不应影响合并。"
open_url "$REPO_URL/settings/rules"
step "检查目标分支规则，不要把 ruleops-shadow (non-blocking) 设置为 required check。"
step "保留现有 CI 作为唯一合并门禁；RuleOps artifact 供人工复核和后续收敛使用。"
if confirm "已确认 RuleOps Shadow 未加入 required checks？"; then
  note "非阻断边界已确认。"
else
  SKIPPED+=("确认 RuleOps Shadow 未进入 required checks")
  warn "不要在证据窗口结束前把 Shadow 设为必需检查。"
fi

finish
